[default]
timeout = 120


[spotify]
title = "Spotify Engineering Blog"
url = "https://engineering.atspotify.com/"
entrySelector = "li.post article"
titleSelector = "h2"
linkSelector = "h2 a"
imageSelector = ".image-holder a img"
